import = [ "~/.config/alacritty/cattpuccin-latte.toml" ]

live_config_reload = true

[window]
dynamic_padding = true
decorations = "None"
opacity = 0.80
blur = true
# startup_mode = "Fullscreen"
dimensions = { columns = 150, lines = 50 }
dynamic_title = false

[font]
size = 14

[font.normal]
family = "Fira Code NerdFont"
style = "Medium"

[font.bold]
family = "Fira Code NerdFont"
style = "SemiBold"

[selection]
save_to_clipboard= true

[cursor.style]
blinking = "Always"
