#!/bin/zsh

alias please="sudo -i"
alias sr="source %"
alias ccp="wl-copy"
alias vcp="wl-paste"
alias fcp="wl-paste | cat"
alias weather="curl 'wttr.in/Tunis?2QF'"
alias _size="du -H --max-depth=1"
alias cdir='cd "${_%/*}"'
alias hl="rg --color always"

# VIM
alias vi="/bin/vim"
alias vim="nvim"
alias v="nvim"

# Better LS
alias ls="eza --icons always"
alias train=\\sl sl="\\/bin/ls"
alias la="eza --all --icons always"
alias l="eza -l --icons always"
alias ll="eza -l --all --icons always  --group-directories-first"
alias lt="eza --all --git-ignore --tree --level=3 --icons always"

# Python
alias venv="source .venv/bin/activate"
alias ipy="ipython --colors=Linux --no-confirm-exit --pylab=agg"

# Flatpaks
alias sdroid="/opt/android-studio/bin/studio.sh"
alias apostrophe="flatpak run org.gnome.gitlab.somas.Apostrophe "
alias code="flatpak run com.visualstudio.code "

# sys
alias dockerclean="docker builder prune -f && docker volune prune && docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi"
