#!/bin/zsh

function getTheme () {
	OS=$(uname -s)
	if [[ $OS == "Linux" ]]; then
		[[ $DESKTOP_SESSION == "gnome" ]] && theme=$(gsettings get org.gnome.desktop.interface color-scheme)
		# kde
	else
	 # Darwin
	fi
	[[ "$theme" == "'prefer-dark'" ]] && theme="dark" || theme="light"
	[[ -n "$theme" ]] && echo $theme || echo "dark"
}

function goingDark () {
	echo "1" > ~/.terminal_theme
	export BAT_THEME="Dracula"
	export DELTA_FEATURE="dark-mode"
	export DARK_THEME="1"

    # Apply to system
    if [[ -n "$1" ]]; then
	    OS=$(uname -s)
        if [[ $OS == "Linux" ]]; then
            [[ $DESKTOP_SESSION == "gnome" ]] && gsettings set org.gnome.desktop.interface color-scheme prefer-dark
            # kde
        else
            # Darwin
        fi
    fi
}

function letThereBeLight () {
	echo "0" > ~/.terminal_theme
	export BAT_THEME="GitHub"
	export DELTA_FEATURE="light-mode"
	export DARK_THEME="0"

    # Apply to system
    if [[ -n "$1" ]]; then
	    OS=$(uname -s)
        if [[ $OS == "Linux" ]]; then
            [[ $DESKTOP_SESSION == "gnome" ]] && gsettings set org.gnome.desktop.interface color-scheme default
            # kde
        else
            # Darwin
        fi
    fi
}

function switchTheme () {
	[[ "$DARK_THEME" == "1" ]] && letThereBeLight foo || goingDark bar
}

function getBranch () {
  git_branch_icon=''
  git_branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  [[ -n "$git_branch" ]] && echo "$git_branch_icon $git_branch"
}

function startd () {
    sudo systemctl start $1
    sudo systemctl enable $1
    sudo systemctl status $1 | grep "Active" | awk '{printf " Status: %s\n", $2}'
}

function bla () {
	echo "hi"
}

function Home () {
    [[ $# -eq 0 ]] && session="Home" || session=$1
    tmux attach-session -t "$session" &> /dev/null || tmux new -s "$session"
}

function myip () {
    curl -s 'https://ipinfo.io' | jq -r '.[]' | head --lines=1
}

function _myip () {
    ip address | grep -o "inet 192.*" | awk '{ print $2 }' | tr / ' ' | xargs
}

function gcm () {
    text=`curl -s curl -s https://whatthecommit.com/ | xmllint --html --xpath '//*[@id="content"]/p[1]/text()' -`
    git add -A && git commit -m "$text"
}

function myConda () {
    __conda_setup="$('/home/mj/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/home/mj/anaconda3/etc/profile.d/conda.sh" ]; then
            . "/home/mj/anaconda3/etc/profile.d/conda.sh"
        else
            export PATH="/home/mj/anaconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
}

function mcd () {
    mkdir -p $1 && cd $1
}

function fcd () {
    RESULTS=$(~/BashScripts/fuzzy-search -d $@)
    [[ -n $RESULTS ]] && cd $RESULTS || echo "No dir was selected"
}

function fvim () {
    RESULTS=$(~/BashScripts/fuzzy-search -f $@)
    [[ -n $RESULTS ]] && $EDITOR $RESULTS || echo "No file/dir was selected"
}

function frg () {
    RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
    FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")"


    INITIAL_QUERY="${*:-}"
    [[ -n $@ ]]  && INITIAL_QUERY="$@"

    fzf --query "$INITIAL_QUERY" \
        --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
        --delimiter : \
        --preview 'bat --color=always {1} --highlight-line {2}' \
        --bind 'enter:become(nvim {1} +{2})'
}

function dumb () {
	look $1 | awk '{ print length, $0 }' | sort -ns |  cut --delimiter=" " --fields=2 | fzf | tee /dev/tty | xargs wl-copy --
}

# WARN: not tested
function customkey () {
    # params: num name command keybindings
    # TODO: the num should be auto

    first_part="org.gnome.settings-daemon.plugins.media-keys.custom-keybinding"
    second_part="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom"

    gsettings set "$first_past:$seconf_part$1/" "name" "$2"
    gsettings set "$first_past:$seconf_part$1/" "command" "$3"
    gsettings set "$first_past:$seconf_part$1/" "keybindings" "$4"

    all_settings=$(gsettings get org.gnome.settings-daemon.plugins.media-keys custom-keybindings)
    all_settings+=('$second_part$1')

    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "$all_settings"
}

function tapClick () {
    isTap=$(gsettings get org.gnome.desktop.peripherals.touchpad tap-to-click)
    if [ "$isTap" = true ]; then
	gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click false
    else
	gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
    fi
}
