require("mason").setup()
require("mason-lspconfig").setup({
	ensure_installed = {
		"eslint_d",
		"json-lsp",
		"pylint",
		"sql_formatter",
		"prettier",
		"stylua",
		"codespell",
		"misspell",
		"sumneko_lua",
		"tailwindcss-language-server",
		"typescript-language-server",
		"gopls",
		"pyright",
		"css-languageserver",
		"emmet-ls",
		"html",
	},
})
