git:
  paging:
    colorArg: never
    pager: delta --paging=never

os:
  editcommand: "nvim"

gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
