git:
  pagers:
    - colorArg: never
    - pager: delta --dark --paging=never

gui:
  nerdFontsVersion: '2'

keybinding:
  universal:
    quit: 'q'
    return: '<esc>'
  commits:
    squashAboveCommits: 's'
  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'

