git:
  paging:
    colorArg: never
    pager: delta --paging=never

os:
  editcommand: 'nvim --server /tmp/neomj --remote-send 2> /dev/null'

gui:
  theme:
    lightTheme: true
    activeBorderColor:
      - black
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
