#!/usr/bin/env bash

# Inspired by ThePrimeagen's Sessionizer

mkdir -p ~/devenv/work ~/devenv/playground ~/devenv/personal ~/devenv/wiki

locations=(
    ~/devenv
    ~/devenv/personal
    ~/devenv/work
)

favLocations=(
    ~/devenv/work/*
    ~/devenv/wiki
    ~/devenv/playground/*
	~/devenv/study/*
	~/devenv/interview/*
)

declare -A repos

repos["config"]=~/.dotfiles

while read -r name path; do
	[[ -z "$name" || -z "$path" ]] && continue
    repos["$name"]="$path"
done <<< $(
	{
		fd "\.git$" -I -H --max-depth 4 --min-depth 2 ${locations[@]} | xargs -r dirname
		fd -g "git$" --max-depth 4 --min-depth 2 -t d --full-path ${locations[@]}
	} \
    | awk -F/ '{print $(NF-2)"-"$(NF-1)"-"$(NF), $0}'
)


while read -r name path; do
	[[ -z "$name" || -z "$path" ]] && continue
    repos["$name"]="$path"
done <<< $(
	ls -d "${favLocations[@]}" 2> /dev/null | awk -F/ '{print $(NF-1)"-"$(NF), $0}'
)

selected=$(printf "%s\n" "${!repos[@]}" | fzf-tmux -p 80% --info=inline)

if [[ -z $selected ]]; then
    exit 0
fi

selected_path=${repos[$selected]}
selected_name=$(echo $selected | awk -F'-' '{print $(NF-1)"-"$NF}' | tr . - )

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] || [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected_path
    tmux attach-session -t $selected_name
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected_path
fi

tmux switch-client -t $selected_name
