#!/bin/bash

PROG=$false

usage() {
  # Display help function
  cat << EOF
  Usage of Fuzzy-Search: 
  
  <Fuzz-Function*> -[rmduih] <Command> | <Fuzz-Function*> -h
	
	-r Start Search at Root dir
	-m Start Search at $HOME
	-d Search Dirs only
	-u The Arguments Unordered
	-i Access Hidden Files
	-h Help

	Functions:
	-- Fuzz-Vim : fvim
	-- Fuzz-Cd : fcd

-- Note: Set alias for all derivative functions.
-- Dependencies: fd, fzf.
-- This could be a wrapper: $PROG
EOF
}

# resolve options
location_arg='./'
hidden=false
order=true
dir=false
while getopts "rmduih" o; do
  case $o in
	r) location_arg='/'
		  ;;
	m) location_arg=$HOME
		;;
	d) dir=true
		;;
	u) order=false
		;;
    i) hidden=true
		;;
    h) usage
		exit 0
		;;
    *) usage 
		exit 1
		;;
  esac 
done

# get arguments only
shift $(($OPTIND-1))
str="$*"

# remove white space if true
[[ "$orde" = "true" ]] && str="$(echo $str | tr -d ' ')" 

[[ "$hidden" = "true" ]] && hid_arg="--hidden" || hid_arg=""


prpt="All> "
preview="bat --color=always {}"
dir_arg=""

[[ "$dir" = "true" ]] && dir_arg="-t d" && prpt="Dirs> " && preview="exa --all --tree --level=3 --icons --git-ignore {}"

RESULTS=$(fd . -E ~/extra $location_arg $hid_arg $dir_arg |
				fzf-tmux -p 80% --query $str \
				--height=40% --layout=reverse --info=inline \
				--prompt=$prpt --preview "$preview")
echo $RESULTS
