#!/bin/bash

#===============================================================================
#   Inspired By: https://github.com/wfxr/tmux-power/blob/master/tmux-power.tmux
#   License: https://wfxr.mit-license.org/2017
#================================================================================

G01=#080808 #232
G02=#121212 #233
G03=#1c1c1c #234
G04=#262626 #235
G05=#303030 #236
G06=#3a3a3a #237
G07=#444444 #238
G08=#4e4e4e #239
G09=#585858 #240
G10=#626262 #241
G11=#6c6c6c #242
G12=#767676 #243


right_arrow_icon=''
left_arrow_icon=''
upload_speed_icon=''
download_speed_icon=''
session_icon=''
user_icon=''
time_icon=''
date_icon=''
show_upload_speed=false
show_download_speed=false
show_web_reachable=false
time_format='%T'
date_format='%F'

FG="#626262"
BG="#262626"

TC='#87ceeb'

tmux set-option -gq status-interval 1
tmux set-option -gq status on

tmux set-option -gq status-fg "$FG"
tmux set-option -gq status-bg "$BG"
tmux set-option -gq status-attr none

tmux set-option -gq @prefix_highlight_fg "$BG"
tmux set-option -gq @prefix_highlight_bg "$FG"
tmux set-option -gq @prefix_highlight_show_copy_mode 'on'
tmux set-option -gq @prefix_highlight_copy_mode_attr "fg=$TC,bg=$BG,bold"
tmux set-option -gq @prefix_highlight_output_prefix "#[fg=$TC]#[bg=$BG]$left_arrow_icon#[bg=$TC]#[fg=$BG]"
tmux set-option -gq @prefix_highlight_output_suffix "#[fg=$TC]#[bg=$BG]$right_arrow_icon"

# Left side of status bar

tmux set-option -gq status-left-bg "$G04"
tmux set-option -gq status-left-fg "G12"
tmux set-option -gq status-left-length 150
user=$(whoami)
LS="#[fg=$G04,bg=$TC,bold] $user_icon $user@#h #[fg=$TC,bg=$G06,nobold]$right_arrow_icon#[fg=$TC,bg=$G06] $session_icon #S "
if "$show_upload_speed"; then
    LS="$LS#[fg=$G06,bg=$G05]$right_arrow_icon#[fg=$TC,bg=$G05] $upload_speed_icon #{upload_speed} #[fg=$G05,bg=$BG]$right_arrow_icon"
else
    LS="$LS#[fg=$G06,bg=$BG]$right_arrow_icon"
fi
if [[ $prefix_highlight_pos == 'L' || $prefix_highlight_pos == 'LR' ]]; then
    LS="$LS#{prefix_highlight}"
fi
tmux set-option -gq status-left "$LS"


# Right side of status bar
tmux set-option -gq status-right-bg "$G04"
tmux set-option -gq status-right-fg "G12"
tmux set-option -gq status-right-length 150
RS="#[fg=$G06]$left_arrow_icon#[fg=$TC,bg=$G06] $time_icon $time_format #[fg=$TC,bg=$G06]$left_arrow_icon#[fg=$G04,bg=$TC] $date_icon $date_format "
if "$show_download_speed"; then
    RS="#[fg=$G05,bg=$BG]$left_arrow_icon#[fg=$TC,bg=$G05] $download_speed_icon #{download_speed} $RS"
fi
if "$show_web_reachable"; then
    RS=" #{web_reachable_status} $RS"
fi
if [[ $prefix_highlight_pos == 'R' || $prefix_highlight_pos == 'LR' ]]; then
    RS="#{prefix_highlight}$RS"
fi
tmux set-option -gq status-right "$RS"

# Window status
tmux set-option -gq window-status-format " #I:#W#F "
tmux set-option -gq window-status-current-format "#[fg=$BG,bg=$G06]$right_arrow_icon#[fg=$TC,bold] #I:#W#F #[fg=$G06,bg=$BG,nobold]$right_arrow_icon"

# Window separator
tmux set-option -gq window-status-separator ""

# Window status alignment
tmux set-option -gq status-justify centre

# Current window status
tmux set-option -gq window-status-current-statys "fg=$TC,bg=$BG"

# Pane border
tmux set-option -gq pane-border-style "fg=$G07,bg=default"

# Active pane border
tmux set-option -gq pane-active-border-style "fg=$TC,bg=$BG"

# Pane number indicator
tmux set-option -gq display-panes-colour "$G07"
tmux set-option -gq display-panes-active-colour "$TC"
