#!/bin/bash
sessions=[ 'Home' , 'Teaching', 'PFE', 'Playground' ]
main="Home"

for s in sessions
do
	tmux new-session -d -s $s
done

# echo "$(tmux list-sessions)" | grep -q "$session" && tmux attach "$session" && exit 0

tmux dettach-client
tmux new-session -d -s $session
cd ~/devenv/ArchiMed

create_window ()
{
	tmux new-window -t $1:$2 -n "$3"
	if [[ -n $4 ]]; then
		tmux send-keys -t $1:$2 "$4" C-m
	fi
}


tmux attach-session -t $main

