#!/bin/bash

session="ArchiMed"

cd ~/devenv/ArchiMed
tmux new-session -d -s $session

window=0
tmux rename-window -t $session:$window 'git'
tmux send-keys -t $session:$window 'git fetch --prune --all' C-m

window=1
tmux new-window -t $session:$window -n 'vim'
cd ArchiMed/Frontend
tmux send-keys -t $session:$window "$EDITOR ." C-m

window=2
cd ArchiMed/Frontend
tmux new-window -t $session:$window -n 'run'

window=3
tmux new-window -t $session:$window -n 'serve'
cd ArchiMed/Frontend
tmux send-keys -t $session:$window 'npm run dev' C-m

tmux attach-session -t $session

