#!/bin/bash

# Inspired by ThePrimeagen


if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/devenv -mindepth 2 -maxdepth 2 -type d | fzf-tmux -p 80% \
        --info=inline --prompt="Dirs> " --preview "exa --all --tree --level=3 --icons --git-ignore {}")

fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
